// User
export const LOGIN_USER = "LOGIN_USER";

// Jobs
export const RECEIVE_JOBS = "RECEIVE_JOBS";
export const FETCH_JOBS = "FETCH_JOBS";

// Organizations
export const UNIQUE_ORGANIZATIONS = "UNIQUE_ORGANIZATIONS";
export const ADD_SELECTED_ORGANIZATIONS = "ADD_SELECTED_ORGANIZATIONS";
export const FILTER_JOBS_BY_ORGANIZATIONS = "FILTER_JOBS_BY_ORGANIZATIONS";
