// User
export const LOGIN_USER = "LOGIN_USER";

// Jobs
export const RECEIVE_JOBS = "RECEIVE_JOBS";
export const FETCH_JOBS = "FETCH_JOBS";
export const FILTER_JOBS = "FILTER_JOBS";

// Organizations
export const UNIQUE_ORGANIZATIONS = "UNIQUE_ORGANIZATIONS";
export const ADD_SELECTED_ORGANIZATIONS = "ADD_SELECTED_ORGANIZATIONS";
export const INCLUDE_JOB_BY_ORGANIZATION = "INCLUDE_JOB_BY_ORGANIZATION";

// Job types
export const UNIQUE_JOB_TYPES = "UNIQUE_JOB_TYPES";
export const ADD_SELECTED_JOB_TYPES = "ADD_SELECTED_JOB_TYPES";
export const INCLUDE_JOB_BY_JOB_TYPE = "INCLUDE_JOB_BY_JOB_TYPE";

// degrees
export const RECEIVE_DEGREES = "RECEIVE_DEGREES";
export const FETCH_DEGREES = "FETCH_DEGREES";
